version: "3"
services:
  app:
    image: "php:5.6-apache"
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80

  composer:
    image: composer
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ./:/app
    restart: never