name: postgres
on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - uses: danielweller-swp/postgresql-action@v2
        with:
          postgresql version: '9.4'  # See https://hub.docker.com/_/postgres for available versions
          postgresql init scripts: 'init-db'
          postgresql conf: 'max_prepared_transactions=100'
