name: postgres
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
        ports:
          - 5432:5432
          # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5 
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: docker ps
        run: docker ps -a
        
      - name: install psql
        run: |
          sudo apt-fast install -y postgresql-client
          psql -h 127.0.0.1 -U postgres -c "create table a ( b integer, c text ); insert into a values(1, '😊');"
          psql -h 127.0.0.1 -U postgres -c "select * from a;"
          ls -la
      
