name: postgres
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
        ports:
          - 5432:5432
          # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: install psql
        run: |
          sudo apt-fast install -y postgresql-client
          psql -h 127.0.0.1 -U postgres -f ./init.sql

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: run php
        env:
            PG_HOST: 127.0.0.1
            PG_USER: postgres
        run: php ./php/index.php

      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: |
          deno --version
          deno run https://deno.land/std/examples/welcome.ts
